# Generated by Django 5.2.1 on 2025-05-24 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='upcyclingrequest',
            name='status',
            field=models.CharField(default='Request Received', max_length=50),
        ),
        migrations.AddField(
            model_name='upcyclingrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upcycling_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
