# Generated by Django 5.2.1 on 2025-05-25 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_artisanprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_completion_days', models.IntegerField(help_text='Estimated days to complete the upcycling project')),
                ('message', models.TextField(blank=True, help_text='Message from the artisan to the requester', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_offers', to='requests.artisanprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='requests.upcyclingrequest')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('request', 'artisan')},
            },
        ),
    ]
