# Generated by Django 5.2.1 on 2025-05-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_upcyclingrequest_accepted_artisan'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcyclingrequest',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='request_images/'),
        ),
    ]
